# Generated by Django 5.2.9 on 2025-12-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="resume_url",
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(default="resumes/legacy.txt", upload_to="resumes/"),
            preserve_default=False,
        ),
    ]
